/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import entidades.Curso;
import entidades.Direccion;
import entidades.Estudiante;
import interfaces.RegistroFachada;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sebastian Moreno
 */
public class MenuCursos extends javax.swing.JPanel {
    
    /**
     * Creates new form MenuCursos
     */
    
    Aplicacion app;
    RegistroFachada R = new RegistroFachada();
    public MenuCursos(Aplicacion app) {
        this.app = app;
        initComponents();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound4 = new gui.PanelRound();
        jLabel4 = new javax.swing.JLabel();
        panelRound5 = new gui.PanelRound();
        jLabel5 = new javax.swing.JLabel();
        panelRound6 = new gui.PanelRound();
        jLabel6 = new javax.swing.JLabel();
        iCantidad = new javax.swing.JTextField();
        iIDCurso = new javax.swing.JTextField();
        iNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        panelRound7 = new gui.PanelRound();
        jLabel8 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound4.setBackground(new java.awt.Color(0, 0, 0));
        panelRound4.setRoundBottomLeft(30);
        panelRound4.setRoundBottomRight(30);
        panelRound4.setRoundTopLeft(30);
        panelRound4.setRoundTopRight(30);
        panelRound4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Agregar Curso");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        panelRound4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 290, 50));

        add(panelRound4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 330, 70));

        panelRound5.setBackground(new java.awt.Color(0, 0, 0));
        panelRound5.setRoundBottomLeft(30);
        panelRound5.setRoundBottomRight(30);
        panelRound5.setRoundTopLeft(30);
        panelRound5.setRoundTopRight(30);
        panelRound5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Eliminar Curso");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        panelRound5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 290, 50));

        add(panelRound5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 330, 70));

        panelRound6.setBackground(new java.awt.Color(0, 0, 0));
        panelRound6.setRoundBottomLeft(30);
        panelRound6.setRoundBottomRight(30);
        panelRound6.setRoundTopLeft(30);
        panelRound6.setRoundTopRight(30);
        panelRound6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Listar Cursos");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        panelRound6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 290, 50));

        add(panelRound6, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 320, 330, 70));

        iCantidad.setText("jTextField1");
        iCantidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iCantidadMouseClicked(evt);
            }
        });
        add(iCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 200, 40));

        iIDCurso.setText("jTextField1");
        add(iIDCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 200, 40));

        iNombre.setText("jTextField1");
        add(iNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 200, 40));

        jLabel1.setText("Cantidad");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, -1, -1));

        jLabel2.setText("id curso");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, -1));

        jLabel3.setText("Nombre");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, -1));

        jLabel7.setText("Se muestra en consola lol.");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 300, -1, -1));

        panelRound7.setBackground(new java.awt.Color(0, 0, 0));
        panelRound7.setRoundBottomLeft(30);
        panelRound7.setRoundBottomRight(30);
        panelRound7.setRoundTopLeft(30);
        panelRound7.setRoundTopRight(30);
        panelRound7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Volver");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        panelRound7.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 80, 20));

        add(panelRound7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 120, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        
        Curso c = new Curso(iIDCurso.getText(), iNombre.getText(), Integer.parseInt(iCantidad.getText()));
        R.agregarCurso(c);
        
      
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        R.eliminarCurso(iIDCurso.getText());
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        R.listarCursos();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void iCantidadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iCantidadMouseClicked

    }//GEN-LAST:event_iCantidadMouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked

        app.mostrarPantallaPrincipal();
    }//GEN-LAST:event_jLabel8MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField iCantidad;
    private javax.swing.JTextField iIDCurso;
    private javax.swing.JTextField iNombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private gui.PanelRound panelRound4;
    private gui.PanelRound panelRound5;
    private gui.PanelRound panelRound6;
    private gui.PanelRound panelRound7;
    // End of variables declaration//GEN-END:variables

}
