/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import Exception.EstructuraException;
import entidades.Direccion;
import entidades.Estudiante;
import interfaces.RegistroFachada;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Sebastian Moreno
 */
public class PantallaEstudiantes extends javax.swing.JPanel {

    /**
     * Creates new form PantallaEstudiantes
     */
    Aplicacion app;
    RegistroFachada r = new RegistroFachada();

    public PantallaEstudiantes(Aplicacion app) {
        this.app = app;
        initComponents();
        estudianteEncontrado.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelRound3 = new gui.PanelRound();
        jLabel3 = new javax.swing.JLabel();
        panelRound4 = new gui.PanelRound();
        jLabel4 = new javax.swing.JLabel();
        iCorreo = new javax.swing.JTextField();
        iCalle = new javax.swing.JTextField();
        iCiudad = new javax.swing.JTextField();
        iTelefono = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        iMatricula = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        iNomrbe = new javax.swing.JTextField();
        iNumero = new javax.swing.JTextField();
        iColonia = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        iMatricula1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        estudianteEncontrado = new javax.swing.JLabel();
        panelRound5 = new gui.PanelRound();
        jLabel13 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound3.setBackground(new java.awt.Color(0, 0, 0));
        panelRound3.setRoundBottomLeft(30);
        panelRound3.setRoundBottomRight(30);
        panelRound3.setRoundTopLeft(30);
        panelRound3.setRoundTopRight(30);
        panelRound3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Buscar por matricula");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        panelRound3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 300, 50));

        add(panelRound3, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 590, 330, 70));

        panelRound4.setBackground(new java.awt.Color(0, 0, 0));
        panelRound4.setRoundBottomLeft(30);
        panelRound4.setRoundBottomRight(30);
        panelRound4.setRoundTopLeft(30);
        panelRound4.setRoundTopRight(30);
        panelRound4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Volver");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        panelRound4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 80, 20));

        add(panelRound4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 120, 40));

        iCorreo.setText("jTextField1");
        add(iCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 200, 40));

        iCalle.setText("jTextField1");
        add(iCalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 200, 40));

        iCiudad.setText("jTextField1");
        add(iCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 360, 200, 40));

        iTelefono.setText("jTextField1");
        add(iTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 200, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Correo Electronico");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ciudad");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nombre");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Telefono");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));

        iMatricula.setText("jTextField1");
        iMatricula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iMatriculaMouseClicked(evt);
            }
        });
        add(iMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 200, 40));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Matricula");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 310, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Calle");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Numero");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Colonia");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, -1, -1));

        iNomrbe.setText("jTextField1");
        add(iNomrbe, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 200, 40));

        iNumero.setText("jTextField1");
        add(iNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 200, 40));

        iColonia.setText("jTextField1");
        add(iColonia, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 200, 40));

        jLabel11.setFont(new java.awt.Font("Franklin Gothic Medium", 2, 48)); // NOI18N
        jLabel11.setText("Menu de Estudiantes");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, -1, -1));

        iMatricula1.setText("jTextField1");
        add(iMatricula1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 370, 200, 40));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Matricula");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        estudianteEncontrado.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        estudianteEncontrado.setForeground(new java.awt.Color(255, 255, 255));
        estudianteEncontrado.setText("Estudiante encontrado : ");
        add(estudianteEncontrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 520, -1, -1));

        panelRound5.setBackground(new java.awt.Color(0, 0, 0));
        panelRound5.setRoundBottomLeft(30);
        panelRound5.setRoundBottomRight(30);
        panelRound5.setRoundTopLeft(30);
        panelRound5.setRoundTopRight(30);
        panelRound5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Registrar Estudiante");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        panelRound5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 290, 50));

        add(panelRound5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 580, 330, 70));

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));
        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 90));

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));
        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1100, 600));
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        try {
            Estudiante e = r.mostrarEstudiante(iMatricula1.getText());

            estudianteEncontrado.setText("Estudiante encontrado : " + e);
            estudianteEncontrado.setVisible(true);
        } catch (EstructuraException ex) {
            Logger.getLogger(PantallaEstudiantes.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked

        app.mostrarPantallaPrincipal();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void iMatriculaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iMatriculaMouseClicked
        iMatricula1.setText("");
    }//GEN-LAST:event_iMatriculaMouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
      // Crear fachada
    RegistroFachada r = new RegistroFachada();

    // Crear y llenar el objeto Dirección
    Direccion direccion = new Direccion();
    direccion.setCalle(iCalle.getText());
    direccion.setNumero(iNumero.getText());
    direccion.setColonia(iColonia.getText());
    direccion.setCiudad(iCiudad.getText());

    // Crear y llenar el objeto Estudiante
    Estudiante e = new Estudiante();
    e.setNombreCompleto(iNomrbe.getText());
    e.setTelefono(iTelefono.getText());
    e.setMatricula(iMatricula.getText());
    e.setCorreoElectronico(iCorreo.getText());
    e.setDireccion(direccion);

        try {
            // Registrar al estudiante
            r.registrarEstudiante(e);
        } catch (EstructuraException ex) {
            Logger.getLogger(PantallaEstudiantes.class.getName()).log(Level.SEVERE, null, ex);
        }

    // Mensaje visual (opcional)
    estudianteEncontrado.setText("Estudiante registrado correctamente");
    }//GEN-LAST:event_jLabel13MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel estudianteEncontrado;
    private javax.swing.JTextField iCalle;
    private javax.swing.JTextField iCiudad;
    private javax.swing.JTextField iColonia;
    private javax.swing.JTextField iCorreo;
    private javax.swing.JTextField iMatricula;
    private javax.swing.JTextField iMatricula1;
    private javax.swing.JTextField iNomrbe;
    private javax.swing.JTextField iNumero;
    private javax.swing.JTextField iTelefono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private gui.PanelRound panelRound3;
    private gui.PanelRound panelRound4;
    private gui.PanelRound panelRound5;
    // End of variables declaration//GEN-END:variables
}
